- hosts: localhost
  connection: local
  become_user: root
  become_method: sudo

  tasks:

  - name: Set up user groups
    become: yes
    group:
      name: '{{ item }}'
      state: present
    with_items: &my-user-groups
      - wheel
      - dialout
      - docker
      - mock
  - name: Add myself to groups
    become: yes
    user:
      name: pviktori
      groups: *my-user-groups

  - name: Install useful software
    become: yes
    dnf:
      name: '{{ item }}'
      state: latest
    with_items:
      - python3
      - git
      - gitk
      - tmux
      - nano
      - exa
      - neovim
      - gedit
      - geany
      - firefox
      - gnome-terminal
      - sqlitebrowser
      
      - quassel-client
      - thunderbird
      - audacity
      
      # tools for further configuration
      - python3dist(psutil)  # for dconf
      - python3dist(click)
      - /usr/bin/unzip
      - /usr/bin/wget

  - name: Install Firefox extensions (system-wide)
    set_fact:
      ff_dir: /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/
  - name: Install Firefox extensions
    become: yes
    shell: |
      cd /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/
      mkdir {{ item.name }}
      cd {{ item.name }}
      wget -O __extension.xpi {{ item.url }}
      unzip __extension.xpi
      rm __extension.xpi
    args:
      creates: '/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}//{{ item.name }}'
    with_items:
       - label: uMatrix
         name: uMatrix@raymondhill.net
         url: https://github.com/gorhill/uMatrix/releases/download/1.3.2/uMatrix.webext.xpi
       - label: Tab Containers
         name: "@testpilot-containers"
         url: https://github.com/mozilla/multi-account-containers/releases/download/5.0.1/multi-account-containers-5.0.1.xpi
       - label: Tree Style Tab
         name: treestyletab@piro.sakura.ne.jp
         url: https://addons.mozilla.org/firefox/downloads/file/858399/tree_style_tab-2.4.11-an+fx-linux.xpi
    loop_control:
      label: "{{ item.label }}"

