- hosts: localhost
  connection: local
  become_user: root

  tasks:

  - name: Set up user groups
    become: yes
    group:
      name: '{{ item }}'
      state: present
    with_items: &my-user-groups
      - wheel
      - dialout
      - docker
      - mock
  - name: Add myself to groups
    become: yes
    user:
      name: pviktori
      groups: *my-user-groups

  - name: Set up RPM fusion
    become: yes
    shell: |
      dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
    args:
      creates: /etc/yum.repos.d/rpmfusion-free.repo

  - name: Install useful software
    become: yes
    dnf:
      state: latest
      name:
      - python3
      - git
      - gitk
      - git-gui
      - tmux
      - nano
      - exa
      - htop
      - ripgrep
      - colordiff

      - neovim
      - gedit
      - geany
      - kate

      - konsole
      - gnome-terminal

      - firefox
      - chromium
      - httpie  # /usr/bin/http

      - sqlitebrowser
      - filelight
      - keepassx

      - gimp
      - inkscape
      - krita

      - mediawriter
      - fuse-exfat

      - mplayer
      - ffmpeg

      - tox
      - python3-pytest
      - python3-twine

      - quassel-client
      - thunderbird
      - audacity

      - evince
      - texlive-pdfjam  # /usr/bin/pdfjam
      - texlive-latex  # /usr/bin/lualatex
      - texlive-latex  # /usr/bin/pdflatex
      - texlive-cm
      - texlive-cm-unicode
      - texlive-cs

      - gnome-shell-extension-system-monitor-applet
      - gnome-screensaver  # /usr/bin/gnome-screensaver-command

      - esptool
      - ampy
      - picocom

      - openscad

      - gcc
      - ccache
      - valgrind
      - gcc-c++  # /usr/bin/g++

      - libtidy-devel

      # tools for further configuration
      - python3dist(psutil)  # for dconf
      - python3dist(click)
      - unzip  # /usr/bin/unzip
      - wget  # /usr/bin/wget

      - fedora-packager

  - name: Install Firefox extensions (fact)
    set_fact:
      ff_dir: /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/
#  - name: Install Firefox extensions
#    become: yes
#    shell: |
#      cd /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/
#      mkdir {{ item.name }}
#      cd {{ item.name }}
#      wget -O __extension.xpi {{ item.url }}
#      unzip __extension.xpi
#      rm __extension.xpi
#    args:
#      creates: '/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}//{{ item.name }}'
#    with_items:
#       - label: Multi-Account Containers
#         name: multi-account-containers
#         url: https://addons.mozilla.org/firefox/downloads/file/3713375/firefox_multi_account_containers-7.3.0-fx.xpi
#       - label: uMatrix
#         name: uMatrix@raymondhill.net
#         url: https://addons.mozilla.org/firefox/downloads/file/3396815/umatrix-1.4.0-an+fx.xpi
#       - label: Tree Style Tab
#         name: treestyletab@piro.sakura.ne.jp
#         url: https://addons.mozilla.org/firefox/downloads/file/3734736/tree_style_tab_-3.7.3-fx.xpi
#         # https://addons.mozilla.org/firefox/downloads/file/3638038/tree_style_tab_-3.5.27-fx.xpi?src=dp-btn-primary
#         # https://addons.mozilla.org/firefox/downloads/file/3524776/tree_style_tab_-3.4.6-fx.xpi
#    loop_control:
#      label: "{{ item.label }}"

